### ISSUE TITLE
SDK not destroying TelephonyManager listener  in Android 12.

### ISSUE THREAD

**Issue by mhd-zulqarnain** [speedchecker/speedchecker-sdk-android#12]
This issue is reproducing on android 11 and 12 in our live app, but unable to reproduce at our end. 
Speedchecker SDK version :4.2.154

Stack trace:

Fatal Exception: java.lang.IllegalStateException: Pid 23191 has exceeded the number of permissible registered listeners. Ignoring request to add.
at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
at android.os.Parcel.createException(Parcel.java:2409)
at android.os.Parcel.readException(Parcel.java:2392)
at android.os.Parcel.readException(Parcel.java:2334)
at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenWithEventList(ITelephonyRegistry.java:1036)
at android.telephony.TelephonyRegistryManager.listenFromListener(TelephonyRegistryManager.java:250)
at android.telephony.TelephonyManager.listen(TelephonyManager.java:5999)
at com.speedchecker.android.sdk.b.a.e$3.run(SpeedTest.java:768)
at java.lang.Thread.run(Thread.java:920)

**Comment by Frederikos** [comment]
Fixed in new version
implementation 'com.speedchecker:android-sdk:4.2.168-android-12-demo'
