### ISSUE TITLE
Missing PendingIntent mutability flag for app target Android 12 (targetSdkVersion 31)

### ISSUE THREAD

**Issue by sterien7** [speedchecker/speedchecker-sdk-android#14]
I see a closed issue but I am still facing this problem, any ideas how to fix it?

**Comment by smafonetech** [comment]
Hi @DenysYakubets @Frederikos @jezowicz 
Facing this below crash whenever try to initialize your SDK. can you please look into this. 
This is happening only for devices with SDK targeting 31

E/AndroidRuntime: FATAL EXCEPTION:
    java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:688)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:675)
        at com.speedchecker.android.sdk.Workers.AlarmReceiver.d(AlarmReceiver.java:189)
        at com.speedchecker.android.sdk.Workers.AlarmReceiver.a(AlarmReceiver.java:127)
        at com.speedchecker.android.sdk.Workers.AlarmReceiver.b(AlarmReceiver.java:131)
        at com.speedchecker.android.sdk.BaseProbe$2.run(BaseProbe.java:84)
        at java.lang.Thread.run(Thread.java:1012)

**Comment by Frederikos** [comment]
This is fixed in new version
implementation 'com.speedchecker:android-sdk:4.2.168-android-12-demo'
