### ISSUE TITLE
Test Fatal Error

### ISSUE THREAD

**Issue by sterien7** [speedchecker/speedchecker-sdk-android#19]
I updated the dependencies on my project and after changing the version of 
`com.google.android.gms:play-services-location:21.0.1` from v20 to v21

After doing so I am stuck on getting `SpeedtestState.TestFatalError`

and on the logcat I see the following:

> FATAL EXCEPTION: Thread-10
Process: com.speedchecker.android.sdk.passive.service, PID: 30298
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.ActivityRecognitionClient, but class was expected (declaration of 'com.google.android.gms.location.ActivityRecognitionClient' appears in /data/app/~~hiRMHb6lEbYDJxSurZH1lA==/com.testapp.staging-OuYRTSg_XQiqY2uBMfBGfQ==/base.apk!classes15.dex)
	at com.speedchecker.android.sdk.c.h.a(IndoorOutdoorHelper.java:122)
	at com.speedchecker.android.sdk.Services.PassiveMeasurementsService.d(PassiveMeasurementsService.java:190)
	at com.speedchecker.android.sdk.Services.PassiveMeasurementsService.d(PassiveMeasurementsService.java:47)
	at com.speedchecker.android.sdk.Services.PassiveMeasurementsService$1.run(PassiveMeasurementsService.java:178)

Do you know what the issue might be? Is there a known solution to that?

**Comment by kustraslawomir** [comment]
> I updated the dependencies on my project and after changing the version of `com.google.android.gms:play-services-location:21.0.1` from v20 to v21
> 
> After doing so I am stuck on getting `SpeedtestState.TestFatalError`
> 
> and on the logcat I see the following:
> 
> > FATAL EXCEPTION: Thread-10
> > Process: com.speedchecker.android.sdk.passive.service, PID: 30298
> > java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.ActivityRecognitionClient, but class was expected (declaration of 'com.google.android.gms.location.ActivityRecognitionClient' appears in /data/app/~~hiRMHb6lEbYDJxSurZH1lA==/com.testapp.staging-OuYRTSg_XQiqY2uBMfBGfQ==/base.apk!classes15.dex)
> > at com.speedchecker.android.sdk.c.h.a(IndoorOutdoorHelper.java:122)
> > at com.speedchecker.android.sdk.Services.PassiveMeasurementsService.d(PassiveMeasurementsService.java:190)
> > at com.speedchecker.android.sdk.Services.PassiveMeasurementsService.d(PassiveMeasurementsService.java:47)
> > at com.speedchecker.android.sdk.Services.PassiveMeasurementsService$1.run(PassiveMeasurementsService.java:178)
> 
> Do you know what the issue might be? Is there a known solution to that?

Have you solved the problem? I have the same...
